### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by mattss** [mattss/pebble-raincheck#3]
All times are currently in UTC. These need to be changed to the correct timezone for the chosen weather location.

As usual, there's a google API for that:
https://developers.google.com/maps/documentation/timezone/

**Comment by adamcheasley** [comment]
+1

**Comment by mattss** [comment]
Just realised the forecast/darksky api already has 'timezone' and 'offset' properties! No need for another api call.

**Comment by adamcheasley** [comment]
+1

**Comment by adamcheasley** [comment]
I'm going to try to only reply with integers.
